### ISSUE TITLE
日志里太多错误： start error: port already used

### ISSUE THREAD

**Issue by worm001** [Yang2635/Magisk-FRPC#1]
程序版本： Magisk-FRPC_v2.9.1, Magisk版本: Magisk-v20.4, 大致上看了一下应该是你脚本设置1分钟登陆一次，这样日志会越来越大。而且效率也不高，FRPC.ini 配置如下 ：
[common]
dns_server = 119.29.29.29
server_addr = 182.139.110.230
server_port = 7000
log_file = /sdcard/Android/frpc/logs/frpc.log
log_level = info
log_max_day = 3
login_fail_exit = false
protocol = kcp

[ADBWIFI]
local_ip = 127.0.0.1
local_port = 5555
remote_port = 15555
use_compression = true
我的frpS.ini 就是默认配置，我不用TLS，也不用加密，只是追求速度，login_fail_exit = false，客户端这个配置很重要，当服务端后于客户端开启的话非常实用！ 这个BUG建议作者在写脚本的时候1分钟进行判断，如果无进程才重启进程，不用1分钟 不管有没有进程都直接登陆，不太好。这样也不会有太多日志。而且效率也比较高。。也谢谢作者搞出这么好用的程序。
日志片断：
2022/05/02 10:43:07 [W] [control.go:179] [503bd203d2de5e42] [ADBWIFI] start error: port already used
2022/05/02 10:43:10 [W] [control.go:179] [ef664433f035a5b6] [ADBWIFI] start error: port already used
2022/05/02 10:43:10 [I] [control.go:315] [6eda71482af764aa] control writer is closing
2022/05/02 10:43:10 [E] [control.go:159] [6eda71482af764aa] work connection closed before response StartWorkConn message: EOF
2022/05/02 10:43:10 [I] [visitor_manager.go:60] [6eda71482af764aa] gracefully shutdown visitor manager
2022/05/02 10:43:10 [W] [service.go:105] login to server failed: i/o deadline reached
2022/05/02 10:43:11 [W] [control.go:179] [f31813c6a719d82d] [ADBWIFI] start error: port already used
2022/05/02 10:43:11 [I] [service.go:178] [6eda71482af764aa] try to reconnect to server...
2022/05/02 10:43:11 [W] [control.go:179] [f4f05dc517fdafdb] [ADBWIFI] start error: port already used
2022/05/02 10:43:11 [I] [service.go:325] [6eda71482af764aa] login to server success, get run id [6eda71482af764aa], server udp port [0]
2022/05/02 10:43:11 [I] [proxy_manager.go:144] [6eda71482af764aa] proxy added: [ADBWIFI]
2022/05/02 10:43:11 [W] [control.go:179] [6eda71482af764aa] [ADBWIFI] start error: port already used
2022/05/02 10:43:13 [W] [control.go:179] [86171917d94e0f21] [ADBWIFI] start error: port already used
2022/05/02 10:43:17 [W] [control.go:179] [3f992a2dd0d27bda] [ADBWIFI] start error: port already used
2022/05/02 10:43:19 [W] [control.go:179] [797faba0784ef87b] [ADBWIFI] start error: port already used
2022/05/02 10:43:21 [I] [service.go:325] [7ba56fd736e3cb9f] login to server success, get run id [7ba56fd736e3cb9f], server udp port [0]
2022/05/02 10:43:21 [I] [proxy_manager.go:144] [7ba56fd736e3cb9f] proxy added: [ADBWIFI]
2022/05/02 10:43:21 [W] [control.go:179] [7ba56fd736e3cb9f] [ADBWIFI] start error: port already used
2022/05/02 10:43:31 [W] [control.go:179] [860402b8d50899bf] [ADBWIFI] start error: port already used
2022/05/02 10:43:37 [W] [control.go:179] [3e7a7f43c103dd3e] [ADBWIFI] start error: port already used
2022/05/02 10:43:40 [W] [control.go:179] [4bd92b4547a3f21e] [ADBWIFI] start error: port already used
2022/05/02 10:43:40 [W] [control.go:179] [9ca3fe90789eb8e8] [ADBWIFI] start error: port already used
2022/05/02 10:43:40 [W] [control.go:179] [503bd203d2de5e42] [ADBWIFI] start error: port already used
2022/05/02 10:43:43 [W] [control.go:179] [ef664433f035a5b6] [ADBWIFI] start error: port already used
2022/05/02 10:43:44 [W] [control.go:179] [f31813c6a719d82d] [ADBWIFI] start error: port already used
2022/05/02 10:43:44 [W] [control.go:179] [f4f05dc517fdafdb] [ADBWIFI] start error: port already used
2022/05/02 10:43:44 [W] [control.go:179] [6eda71482af764aa] [ADBWIFI] start error: port already used
2022/05/02 10:43:46 [W] [control.go:179] [86171917d94e0f21] [ADBWIFI] start error: port already used
2022/05/02 10:43:50 [W] [control.go:179] [3f992a2dd0d27bda] [ADBWIFI] start error: port already used
2022/05/02 10:43:52 [W] [control.go:179] [797faba0784ef87b] [ADBWIFI] start error: port already used
2022/05/02 10:43:54 [W] [control.go:179] [7ba56fd736e3cb9f] [ADBWIFI] start error: port already used
2022/05/02 10:44:01 [I] [service.go:325] [3b9726809b876bd9] login to server success, get run id [3b9726809b876bd9], server udp port [0]
2022/05/02 10:44:01 [I] [proxy_manager.go:144] [3b9726809b876bd9] proxy added: [ADBWIFI]
2022/05/02 10:44:01 [W] [control.go:179] [3b9726809b876bd9] [ADBWIFI] start error: port already used

**Comment by Yang2635** [comment]
模块设定的是每分钟检测一次，除了程序启动外，仅在frpc的配置文件发生改动时会执行配置文件重载；文件未发生改动即退出，不会产生额外的行为。

模块运行本身是不产生日志的，为方便排查frpc穿透的错误，该日志为frpc程序运行的日志并建议开启的，模块携带的配置文件里日志参数我默认设置的为info级别，并且仅保留近3天的日志，超出3天自动删除旧日志，若不需要该日志可以通过调节其日志等级减少frpc运行时日志的输出。

此处根据您提供的frpc运行的日志，应该是你服务器端的15555端口被占用所致，导致frpc程序一直输出log，可排查下服务器端的15555端口使用情况。

关于模块，后期会进一步优化下相关流程逻辑，感谢支持！
