### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by Ran-Xing** [Yang2635/Magisk-FRPC#5]
1. 有几次开机 frpc 并没有自启，但是等待几分钟就好了，请问是设置了定时检测吗？
2. 低于20%结束frpc，请问开始充电 且大于20%会重新启动嘛？
3. 请问如果服务端链接不上有做重试机制嘛？

**Comment by Yang2635** [comment]
1.是
2.会。低于20%未充电会自动结束进程，充电状态或电量高于20%后就自动重新启动
3.重试机制得自己在frpc配置文件中配置，可阅读一下frpc相关的配置文件，模块只做基本的服务状态监控。

**Comment by Ran-Xing** [comment]
感谢大佬🙏🏻
